### ISSUE TITLE
This repo wants renaming

### ISSUE THREAD

**Issue by futuresocks** [arnoldclark/front-end-interview#7]
Just taking a nosey in prep for a thing tomorrow and noticed some inconsistencies we probably want to address - this whole repo is called `front-end-mob-programming`, when it's not really: it's a repo where we have instructions for our Front End Interview process with the option to partake in *either* a front end mob programming session or a show and tell. As such, we should probably rename it accordingly. `front-end-interview`, for lack of a better idea?

The naming of the repo probably isn't helping the recruitment process either, since I've just seen an invite go out to a candidate inviting them to a... front end mob programming session. When again, it isn't. That's up to the candidate.

**Comment by johnmccollum** [comment]
This is a totally fair point. I was worried about 404ing candidates, but looking at [this blog post](https://github.blog/2013-05-16-repository-redirects-are-here/), it looks as if web traffic, fetches, clones etc. will be redirected.

Let's try to schedule this in at a quiet moment. Are we happy with `front-end-interview`?

**Comment by futuresocks** [comment]
> Let's try to schedule this in at a quiet moment. Are we happy with `front-end-interview`?

Makes sense to me!

**Comment by johnmccollum** [comment]
Well that seems to have worked!

🎉

**Comment by futuresocks** [comment]
> Well that seems to have worked!
> 
> 🎉

Yaldi!
